version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build:
    docker: # run the steps with Docker
      - image: markhobson/maven-chrome:latest # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - run: mvn clean
      - run: mvn compile
      - run: mvn test
      - run: mvn cluecumber-report:reporting
      - run: mvn jacoco:report
      - store_artifacts:
          path: target/cucumber-html-report
      - store_artifacts:
          path: target/site/jacoco
      - store_test_results:
          path: target/surefire-reports